### ISSUE TITLE
Editing pasted text looses formatting

### ISSUE THREAD

**Issue by Stephane-30** [Daniele-rolli/Beaver-Notes#149] opened 2024-03-17 10:18 UTC
**Bug Description**
Copy and pasting text from a **PDF**  works fine. However, when making changes to the text it will instantly loose its formatting and be displayed all on one line. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Copy text with paragraphs from a **PDF**
2. Paste into a Beaver note with Ctrl-C or Shift-Ctrl-C
3. Add a random space or char into any position
4. The whole text collapses into one line

**Expected Behaviour**
Pasted text to keep its format.

**Screenshots**
Copied text from a PDF and pasted into Beaver note. Added a random space and text will collapse.

![after-pasting](https://github.com/Daniele-rolli/Beaver-Notes/assets/72917674/25fb28e7-ceb8-46e7-9e6c-222df85f9945)
![adding a space](https://github.com/Daniele-rolli/Beaver-Notes/assets/72917674/04c7e6c7-b4f8-4b53-a0d2-5fc9dd351022)

**Desktop (please complete the following information):**
- OS: Garuda Linux Gnome (latest)
- Application Version: Version 2.9.0

**Additional Context**
I also tried to copy text first into a plain text editor to remove any formatting but that doesn't make any difference either.

**Comment by Daniele-rolli** [comment] 2024-03-17 10:29
Thank you for reporting this issue. I'll look into it and get it fixed.

**Comment by Stephane-30** [comment] 2024-03-17 10:54
Hi Daniele

Thanks for your quick reply. I did some more testing and realised that the
bug only applies to pasting text from PDF files. Pasting from websites
works fine (I may have copied text from a PDF viewed on a website). I've
changed the relevant text in my bug report.

I think Beaver is a fantastic project and I hope it will develop.
Especially the combination with an Android app and Desktop is what I'm
really excited about.
For the time being I will probably only be able to help by posting the
occasional comment and/or bug report. My coding skills are not up to
scratch to help on that front (however, I would love to!)

Best wishes
Stephane

**Comment by Daniele-rolli** [comment] 2024-03-17 14:59
Thanks for the additional details, and I'm glad to hear you enjoy Beaver. I've improved how Beaver handles pasting, so text should no longer collapse into a single line when editing. However, I've also noticed that certain apps, especially PDF viewers, do not retain formatting when copying text. For example, text copied from Preview on macOS appears to the app as a single paragraph and collapses, whereas text copied from Firefox is handled correctly.

To test this, you can clone the development branch and then follow the documentation available [here](https://danieles-organization.gitbook.io/beaver-notes). You might want to back up your notes before making any changes. If the issue persists, please don't hesitate to inform me. Additionally, you can try copying text from the same PDF using different apps, as some may not provide enough data for proper formatting.

Feel free to reach out with any ongoing issues or questions.  I greatly appreciated your willingness to help develop Beaver!

**Comment by Daniele-rolli** [comment] 2024-03-18 07:02
By the way, let me know if the issue is still present, as I'm waiting for confirmation to pack version 3.0.0

**Comment by Stephane-30** [comment] 2024-03-18 07:34
Hi Daniele

I have branched the project and set up the dev environment on my Linux PC.
I can build and run BN fine. I would assume I'm on the latest build but the
PDF paste problem is still present.
I use Evince PDF viewer.

Stephane

**Comment by Stephane-30** [comment] 2024-03-18 07:49
I obviously meant 'forked' the project.

**Comment by Daniele-rolli** [comment] 2024-03-18 07:50
Got it. I'll try it on my Fedora install and figure out why it still doesn't work.

**Comment by Daniele-rolli** [comment] 2024-03-18 08:10
Okay, I see the issue. Basically, you might have forked the main branch, which doesn't contain the updated code, as commits are primarily pushed to the development branch and then merged into main when ready for production. Here's what pasting looks like:

Fedora ~ Evince - branch: Development - V. 3.0.0

https://github.com/Daniele-rolli/Beaver-Notes/assets/67503004/67863252-b376-4e70-aa9a-6b437598c71c

macOS / Fedora ~ Evince - branch: main - V. 2.9.0

https://github.com/Daniele-rolli/Beaver-Notes/assets/67503004/c0bd5bcc-442c-4967-a28e-0ab39aa1e9dc

As you can see, the text in version 3.0.0 doesn't collapse upon editing, whereas the one in version 2.9.0 does.

Additional resource: [pdf used ](https://huh.harvard.edu/sites/hwpi.harvard.edu/files/herbaria/files/hpb_volume28_number2_lores.pdf?m=1703699486)

**Comment by Stephane-30** [comment] 2024-03-18 08:17
That's good news. I look forward to the  updated version and will test it
thoroughly.

**Comment by Stephane-30** [comment] 2024-03-18 10:11
I've updated my local branch and the copy/paste from a PDF works fine now.
Thank you.

**Closed** 2024-03-18 11:17 UTC
Labels: bug
